//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KajolBezol.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KajolBezol.UI.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN CONTACT.
        /// </summary>
        internal static string AdminContactMsg {
            get {
                return ResourceManager.GetString("AdminContactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bid to buy US${0}.
        /// </summary>
        internal static string BidConfirmBuy {
            get {
                return ResourceManager.GetString("BidConfirmBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bid to sell US${0}.
        /// </summary>
        internal static string BidConfirmSell {
            get {
                return ResourceManager.GetString("BidConfirmSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid to Buy.
        /// </summary>
        internal static string BidToBuy {
            get {
                return ResourceManager.GetString("BidToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid to Sell.
        /// </summary>
        internal static string BidToSell {
            get {
                return ResourceManager.GetString("BidToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLBOARD.
        /// </summary>
        internal static string BillboardTab {
            get {
                return ResourceManager.GetString("BillboardTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your US$ {0} buy bid has been matched to a peer transaction under code #{1}. Send a WhatsApp message to the admin in order to coordinate the details of the transaction..
        /// </summary>
        internal static string BuyMatched {
            get {
                return ResourceManager.GetString("BuyMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Price.
        /// </summary>
        internal static string BuyPriceTxt {
            get {
                return ResourceManager.GetString("BuyPriceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Right Away.
        /// </summary>
        internal static string BuyRightNow {
            get {
                return ResourceManager.GetString("BuyRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your buy bid for US${0} still has no match. We&apos;ll let you know today once it gets matched..
        /// </summary>
        internal static string BuyStillNoMatch {
            get {
                return ResourceManager.GetString("BuyStillNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY.
        /// </summary>
        internal static string BuyVerbTxt {
            get {
                return ResourceManager.GetString("BuyVerbTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot continue trading until your current transaction is cleared. Check the billboard for state and details about your current transaction..
        /// </summary>
        internal static string CannotTradePrevOperation {
            get {
                return ResourceManager.GetString("CannotTradePrevOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the billboard for additional info..
        /// </summary>
        internal static string CheckBillboardForDetails {
            get {
                return ResourceManager.GetString("CheckBillboardForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check new notifications and the billboard periodically. We&apos;ll let you know once your bid is matched..
        /// </summary>
        internal static string CheckBillboardPeriodically {
            get {
                return ResourceManager.GetString("CheckBillboardPeriodically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ClosedTitle {
            get {
                return ResourceManager.GetString("ClosedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this moment trading is closed. Check days and time when trading is open. .
        /// </summary>
        internal static string ClosedTxt {
            get {
                return ResourceManager.GetString("ClosedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Try again later..
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCHANGE RATE.
        /// </summary>
        internal static string ExchangeRateMsg {
            get {
                return ResourceManager.GetString("ExchangeRateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string ExitTxt {
            get {
                return ResourceManager.GetString("ExitTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either user or password are wrong.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available. Download it first to be able to log in.
        /// </summary>
        internal static string NewVersionBody {
            get {
                return ResourceManager.GetString("NewVersionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        internal static string NewVersionTitle {
            get {
                return ResourceManager.GetString("NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bids at this time. Click on Trade tab and bid to buy or sell from your peers..
        /// </summary>
        internal static string NoBids {
            get {
                return ResourceManager.GetString("NoBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string ProfileTab {
            get {
                return ResourceManager.GetString("ProfileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AMOUNT.
        /// </summary>
        internal static string SelectAmountTxt {
            get {
                return ResourceManager.GetString("SelectAmountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your US$ {0} sell bid has been matched to a peer transaction under code #{1}. Send a WhatsApp message to the admin in order to coordinate the details of the transaction..
        /// </summary>
        internal static string SellMatched {
            get {
                return ResourceManager.GetString("SellMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        internal static string SellPriceTxt {
            get {
                return ResourceManager.GetString("SellPriceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Right Away.
        /// </summary>
        internal static string SellRightNow {
            get {
                return ResourceManager.GetString("SellRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sell bid for US${0} still has no match. We&apos;ll let you know today once it gets matched..
        /// </summary>
        internal static string SellStillNoMatch {
            get {
                return ResourceManager.GetString("SellStillNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELL.
        /// </summary>
        internal static string SellVerbTxt {
            get {
                return ResourceManager.GetString("SellVerbTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with user name and password.
        /// </summary>
        internal static string SignIn2 {
            get {
                return ResourceManager.GetString("SignIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInBtnTxt {
            get {
                return ResourceManager.GetString("SignInBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought US${0}.
        /// </summary>
        internal static string TransactionConfirmBuy {
            get {
                return ResourceManager.GetString("TransactionConfirmBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold US${0}.
        /// </summary>
        internal static string TransactionConfirmSell {
            get {
                return ResourceManager.GetString("TransactionConfirmSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTION TYPE.
        /// </summary>
        internal static string TransactionTypeTxt {
            get {
                return ResourceManager.GetString("TransactionTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADE.
        /// </summary>
        internal static string TransactTab {
            get {
                return ResourceManager.GetString("TransactTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage and Privacy Policies.
        /// </summary>
        internal static string UsePolicyTxt {
            get {
                return ResourceManager.GetString("UsePolicyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeTxt {
            get {
                return ResourceManager.GetString("WelcomeTxt", resourceCulture);
            }
        }
    }
}
